### ISSUE TITLE
Update dev version to 1.21

### ISSUE THREAD

**Issue by alexmartz710** [Mikedeejay2/SimpleStackPlugin#104]
I'd like an update of the dev version to 1.21 if possible.. I tried compiling it myself for 1.21 since I don't think much of the code has changed since 1.20.6 and I was able to compile it but it appears to be that I need updated library files since it fails to load the plugin.  I'm referring to Mikedeejay2Lib files since that's the only thing I haven't changed and I'm not sure how to update those since you upload them directly into github already compiled, I can compile the files myself but they look much different then the ones in your Maven repo which have timestamps and stuff. Thank you so much for this plugin I really enjoy using it on my server and a lot of other players love it too!

**Comment by TheFaik** [comment]
Please!

**Comment by Mikedeejay2** [comment]
Thanks for writing this issue! I hadn't realized Paper was releasing server versions for 1.21 yet. I will work on the update for 1.21 today. Like you said, I don't think there are large changes between 1.20.6 and 1.21, but the NMS mappings and Mikedeejay2Lib still need to be updated. 

Also, a note on Mikedeejay2Lib: If you have the repo cloned to your computer, you can build it locally with the command `mvn clean install`. That command will produce the same format of files you see in the GitHub repo, except located in your local Maven repository. Then, you can build SimpleStack with the local build of Mikedeejay2Lib.

**Comment by TheFaik** [comment]
> Thanks for writing this issue! I hadn't realized Paper was releasing server versions for 1.21 yet. I will work on the update for 1.21 today. Like you said, I don't think there are large changes between 1.20.6 and 1.21, but the NMS mappings and Mikedeejay2Lib still need to be updated.
> 
> Also, a note on Mikedeejay2Lib: If you have the repo cloned to your computer, you can build it locally with the command `mvn clean install`. That command will produce the same format of files you see in the GitHub repo, except located in your local Maven repository. Then, you can build SimpleStack with the local build of Mikedeejay2Lib.

=D

**Comment by alexmartz710** [comment]
I've updated the Mikedeejay2Lib files and compiled the plugin with it, however it still doesn't load correctly I get this error
`[14:00:23 INFO]: [SimpleStack] Enabling SimpleStack v2.0.1-DEV-SNAPSHOT
[14:00:23 INFO]: [SimpleStack] SimpleStack is powered by Mikedeejay2Lib, a collection of open source resources for developers to use.
[14:00:23 ERROR]: Error occurred while enabling SimpleStack v2.0.1-DEV-SNAPSHOT (Is it up to date?)
        at SimpleStack-2.0.1-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.config.SimpleStackConfigImpl$UniqueItemFile.<init>(SimpleStackConfigImpl.java:233) ~[SimpleStack-2.0.1-DEV-SNAPSHOT.jar:?]
        at SimpleStack-2.0.1-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.config.SimpleStackConfigImpl.<init>(SimpleStackConfigImpl.java:35) ~[SimpleStack-2.0.1-DEV-SNAPSHOT.jar:?]
        at SimpleStack-2.0.1-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.SimpleStack.onEnable(SimpleStack.java:72) ~[SimpleStack-2.0.1-DEV-SNAPSHOT.jar:?]
        at SimpleStack-2.0.1-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.config.SimpleStackConfigImpl$UniqueItemFile$UniqueStrategy.<clinit>(SimpleStackConfigImpl.java:295) ~[SimpleStack-2.0.1-DEV-SNAPSHOT.jar:?]
        at SimpleStack-2.0.1-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.config.SimpleStackConfigImpl$UniqueItemFile$UniqueStrategy.<clinit>(SimpleStackConfigImpl.java:291) ~[SimpleStack-2.0.1-DEV-SNAPSHOT.jar:?]
[14:00:23 INFO]: [SimpleStack] Disabling SimpleStack v2.0.1-DEV-SNAPSHOT`
It's probably something to do with NMS mappings? Not sure honestly I don't understand the error, looks like it's still detecting it as a 1.20.6 plugin

**Comment by alexmartz710** [comment]
Oh okay, that's an error from SimpleStackConfigImpl.java about $UniqueItemFile missing I guess
![image](https://github.com/Mikedeejay2/SimpleStackPlugin/assets/63435223/661208ab-1a4f-4352-9c2a-9fa5523be34c)

**Comment by alexmartz710** [comment]
I forked both the repo and simplestackplugin and did a workflow to test if it worked that way but it did not, if you want to take a look at all I did here are the links [SimpleStackPluginFork](https://github.com/alexmartz710/SimpleStackPlugin) [Mikedeejay2-Maven-Repo-Fork](https://github.com/alexmartz710/Mikedeejay2-Maven-Repo)

**Comment by Mikedeejay2** [comment]
Great work! You're on the right track, but updating this plugin is usually a pain in one way or another. The error we both experienced was because Paper changed how Item stacks work internally. 

I was hoping to fit the update for 1.21 into a single commit, but it looks like a couple of things will take some additional work. 
I created a separate branch for the 1.21 update you can find [here](https://github.com/Mikedeejay2/SimpleStackPlugin/tree/update/1.21). It's compilable and functional (hopefully), but I'd like to fix a couple of things before I publish the changes to the develop branch.

**Comment by alexmartz710** [comment]
I see thank you for your work! I would love to learn more about coding stuff like this, where does Paper publish the changes they do?

**Comment by Mikedeejay2** [comment]
Paper publishes changes to their [repository](https://github.com/PaperMC/Paper). By cloning the repository and then running the commands found in the read me of the repository, you can browse Minecraft source code and paper changes. You can also look at their pull requests and issues. There are many of them and some might contain useful information, such as [the pull request that changed ItemStack logic](https://github.com/PaperMC/Paper/pull/10852).

**Comment by alexmartz710** [comment]
Awesome thank you! I am testing it in a 1.21 test server and it works fine I did just get spammed with this `[18:50:09 ERROR]: SimpleStack could not find material of ID "MINECRAFT:WHEAT"
        at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.util.NmsConverters.itemToMaterial(NmsConverters.java:94) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
         at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.bytecode.transformers.advice.TransformItemGetMaxStackSize.bridgedMethod(TransformItemGetMaxStackSize.java:56) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]` Until I removed some wheat from a chest or until I got rid of villagers trying to pick up wheat, testing the villagers it seems like it wasn't them but not sure, their inventory could have been full from before

**Comment by alexmartz710** [comment]
It is the villager inventory here is the full error `[19:31:53 ERROR]: SimpleStack could not find material of ID "MINECRAFT:WHEAT"
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.MINECRAFT:WHEAT
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:130) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.util.NmsConverters.itemToMaterial(NmsConverters.java:94) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
        at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.bytecode.transformers.advice.TransformItemGetMaxStackSize.bridgedMethod(TransformItemGetMaxStackSize.java:56) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
        at com.mikedeejay2.simplestack.bytecode.AdviceBridge.getItemMaxStackSize(AdviceBridge.java:126) ~[?:?]
        at net.minecraft.world.item.Item.getDefaultMaxStackSize(Item.java:110) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.ai.behavior.TradeWithVillager.tick(TradeWithVillager.java:57) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.ai.behavior.TradeWithVillager.tick(TradeWithVillager.java:25) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:78) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.ai.behavior.GateBehavior.tickOrStop(GateBehavior.java:72) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:455) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:404) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:258) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:253) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:948) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3415) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:680) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3118) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.Mob.tick(Mob.java:447) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:300) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1189) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:983) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:736) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:716) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-36-dd31654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-36-dd31654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Mikedeejay2** [comment]
Yeah, I get that on my end too. It looks like 1.21 changed that, where the Item ID didn't have `minecraft:` at the start but now it does. I just pushed a fix to the 1.21 branch, let me know if it fixes that issue for you as well.

**Comment by alexmartz710** [comment]
Looks like it's working! I'll keep testing and let you know if I find any other bugs
