### ISSUE TITLE
Please support JAVA 23

### ISSUE THREAD

**Issue by TheFaik** [Mikedeejay2/SimpleStackPlugin#109]
Please support JAVA 23

**Comment by TheFaik** [comment]
```
[19:17:09 INFO]: [SimpleStack] SimpleStack is powered by Mikedeejay2Lib, a collection of open source resources for developers to use.
[19:17:10 INFO]: [SimpleStack] Loading mappings for Minecraft version 1.21.1...
[19:17:10 INFO]: [SimpleStack] Installing Simple Stack transformer, this may take a moment...
[19:17:10 INFO]: [SimpleStack] Applying transformations, this may take a moment...
[19:17:10 ERROR]: [SimpleStack]
---- SimpleStack Crash Report ----

Time: 2024/11/23 19:17:10
Description: Exception while injecting Advice bridge

java.lang.UnsupportedOperationException: Cannot get defined package using reflection: Java 23 (67) is not supported by the current version of Byte Buddy which officially supports Java 22 (66) - update Byte Buddy or set com.mikedeejay2.simplestack.internal.bytebuddy.experimental as a VM property
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.internal.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.getDefinedPackage(ClassInjector.java:479)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.internal.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:251)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.internal.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.bytecode.SimpleStackClassInjector.inject(SimpleStackClassInjector.java:43)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.bytecode.SimpleStackAgent.injectAdviceBridge(SimpleStackAgent.java:113)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.bytecode.SimpleStackAgent.install(SimpleStackAgent.java:84)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.SimpleStack.installAndTransform(SimpleStack.java:130)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.SimpleStack.onEnable(SimpleStack.java:77)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:1575)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at java.base/java.lang.Thread.getStackTrace(Thread.java:2389)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.debug.CrashReport.getHead(CrashReport.java:105)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.debug.CrashReport.getReport(CrashReport.java:312)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.debug.CrashReport.execute(CrashReport.java:274)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.SimpleStack.doCrash(SimpleStack.java:176)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.bytecode.SimpleStackAgent.injectAdviceBridge(SimpleStackAgent.java:117)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.bytecode.SimpleStackAgent.install(SimpleStackAgent.java:84)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.SimpleStack.installAndTransform(SimpleStack.java:130)
        at SimpleStack-2.0.0-98.jar//com.mikedeejay2.simplestack.SimpleStack.onEnable(SimpleStack.java:77)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:374)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by Mikedeejay2** [comment]
This should be fixed in the latest version, let me know if you have any issues
