### ISSUE TITLE
would be nice to have support for Paper 1.17.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Mikedeejay2/SimpleStackPlugin#82]
would be nice to have support for Paper 1.17.1

```
[23:41:34] [Server thread/ERROR]: Error occurred while enabling SimpleStack v1.3.6 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.version.VersionEnum.v1_17_R1
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.version.VersionEnum.valueOf(VersionEnum.java:8) ~[?:?]
	at com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.version.MinecraftVersion.calcVersionEnum(MinecraftVersion.java:99) ~[?:?]
	at com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.version.MinecraftVersion.<init>(MinecraftVersion.java:32) ~[?:?]
	at com.mikedeejay2.simplestack.internal.mikedeejay2lib.PluginBase.onEnable(PluginBase.java:43) ~[?:?]
	at com.mikedeejay2.simplestack.Simplestack.onEnable(Simplestack.java:32) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:41:34] [Server thread/INFO]: [SimpleStack] Disabling SimpleStack v1.3.6
[23:41:34] [Server thread/ERROR]: Error occurred while disabling SimpleStack v1.3.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.mikedeejay2.simplestack.config.Config.isModified()" because "this.config" is null
	at com.mikedeejay2.simplestack.Simplestack.onDisable(Simplestack.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527) ~[patched_1.17.1.jar:git-Paper-137]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-137]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-137]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Mikedeejay2** [comment]
Thanks for the issue! This has been resolved with version 1.3.7.
